Repository chris-hinson/waste, pull requests merged in 2022-11, with the labels that each got.

#36 infinite world gen with seeding
  assets/monsters/rad_duck.png
  src/backgrounds.rs
  src/camera.rs
  src/main.rs
  src/player.rs
  src/wfc.rs
  src/world.rs
Labels: bug, help wanted

#45 [WIP] Battling , Game Core and Game Progress
  src/backgrounds.rs
  src/battle.rs
  src/main.rs
  src/monster.rs
  src/player.rs
  src/world.rs
Labels: help wanted, high priority, core

#51 Monsters spawn with random type in battles and health regen when winning or losing a battle
  assets/backgrounds/battlescreen_desert_1.png
  assets/backgrounds/battlescreen_desert_1_with_shadow.png
  assets/backgrounds/broken_car_1.png
  assets/backgrounds/multiplayer_screen.png
  assets/backgrounds/overworld_tilesheet.png
  assets/backgrounds/start_screen.png
  assets/backgrounds/start_screen_with_text.png
  assets/backgrounds/test_scroll_background.png
  assets/characters/npc_sprite.png
  assets/credits/gavin_credit.png
  assets/monsters/clean_monster.png
  assets/monsters/ember_monster.png
  assets/monsters/ember_monster_big.png
  assets/monsters/ember_monster_resized.png
  assets/monsters/rad_monster.png
  assets/monsters/robot_monster.png
  src/backgrounds.rs
  src/battle.rs
  src/main.rs
  src/monster.rs
  src/world.rs
Labels: core

#48 [WIP] communicating between threads + players
  src/battle.rs
  src/game_client.rs
  src/main.rs
  src/multiplayer_menu.rs
  src/start_menu.rs
Labels: high priority, networking

#52 [WIP] single player game core
  assets/monsters/toxic_monster.png
  src/backgrounds.rs
  src/battle.rs
  src/main.rs
  src/monster.rs
  src/player.rs
  src/world.rs
Labels: help wanted, core
